// Import necessary dependencies and files
import 'package:dio/dio.dart';
import 'package:green_grove/core/constants/constants.dart';
import 'package:retrofit/dio.dart';
import 'package:retrofit/http.dart';
import '../../models/CarbonFootprintModel.dart';

// Part file generated by retrofit containing the implementation of CarbonFootprintApiService
part 'carbon_footprint_api_service.g.dart';

// Retrofit annotation to define the base URL for API requests
@RestApi(baseUrl: carbonFootprintBaseUrl)
abstract class CarbonFootprintApiService {
  // Factory constructor for creating instances of CarbonFootprintApiService
  factory CarbonFootprintApiService(Dio dio) = _CarbonFootprintApiService;

  // Retrofit annotation for making a POST request to the '/predict' endpoint
  @POST('/predict')
  // Future method returning an HttpResponse with a list of CarbonFootprintModel
  Future<HttpResponse<List<CarbonFootprintModel>>> predictCarbonFootprint(
      @Body() String activityType,         // Body parameter for activity type
      @Body() double quantity,             // Body parameter for quantity
      @Body() String vehicleType,          // Body parameter for vehicle type
      @Body() double distance,             // Body parameter for distance
      @Body() double fuelEfficiency,       // Body parameter for fuel efficiency
      @Body() String foodType,             // Body parameter for food type
      );
}
